# Generated by Django 5.1.4 on 2024-12-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='item/')),
            ],
        ),
    ]
